site_name: Horus
repo_url: https://github.com/rikemorais/rikemorais.project.horus
repo_name: Horus Project
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.jpeg
  favicon: assets/logo.jpeg

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins: 
  - mkdocstrings
