[tool.poetry]
name = "horus"
version = "0.1.0"
description = ""
authors = ["Henrique Morais <rikeaju@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
black = "^23.3.0"
isort = "^5.12.0"
pydocstyle = "^6.3.0"
pytest = "^7.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
